apiVersion: v1
kind: Namespace
metadata:
  name: auth-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-server
  namespace: auth-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: ghcr.io/astral-sh/uv:python3.14-trixie
          imagePullPolicy: IfNotPresent
          command: ["uv", "run", "/app/auth_server.py"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: code
              mountPath: /app
              readOnly: true
      volumes:
        - name: code
          configMap:
            name: auth-server
---
apiVersion: v1
kind: Service
metadata:
  namespace: auth-server
  name: auth-server
  labels:
    app: auth-server
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: auth-server
